name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Show Paths
      run: ls
    - name: Benchmark
      run: cd src/Benchmark.Http.Sample.ConsoleApp; sudo dotnet run -c Release "https://reqbin.com/echo"
    - uses: actions/upload-artifact@v2
      with:
        path: src/Benchmark.Http.Sample.ConsoleApp/BenchmarkDotNet.Artifacts/results/Benchmark.Http.Sample.ConsoleApp.BenchmarkHttp-report.html
